server:
    port: 8091
    address: localhost
spring:
    application:
        name: KeepAccount
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/keep_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 12345678
    servlet:
        multipart:
            max-file-size: 1000MB
            max-request-size: 1000MB
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher

mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    root: INFO
